version: "3"

services:
  socket_gateway:
    volumes:
      - ./socket-gateway:/code
    environment:
      - NODE_ENV=development
    command: yarn watch

  api_gateway:
    volumes:
      - ./api-gateway:/code
    environment:
      - NODE_ENV=development
    command: yarn watch