version: "3"

services:
  socket_getway:
    container_name: socket_getway
    build: ./socket-getway
    image: socket-getway
    ports:
      - "3000:3000"
    depends_on:
      - socket_getway_redis
      - rabbitmq
    command: yarn start

  socket_getway_redis:
    container_name: socket_getway_redis
    image: redis:alpine
    volumes:
      - ./data/socket_getway_redis:/data

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management-alpine
    ports:
      # port to amq management
      - "15672:15672"
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq