version: "3"

services:
  socket_gateway:
    container_name: socket_gateway
    build: ./socket-gateway
    image: socket-gateway
    ports:
      - "3000:80"
    depends_on:
      - socket_gateway_redis
      - rabbitmq
      - api_gateway
    command: yarn start

  socket_gateway_redis:
    container_name: socket_gateway_redis
    image: redis:alpine
    volumes:
      - ./data/socket_gateway_redis:/data

  api_gateway:
    container_name: api_gateway
    build: ./api-gateway
    image: api-gateway
    ports:
      - "3100:80"
    depends_on:
      - api_gateway_redis
      - rabbitmq
    command: yarn start

  api_gateway_redis:
    container_name: api_gateway_redis
    image: redis:alpine
    volumes:
      - ./data/api_gateway_redis:/data

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management-alpine
    ports:
      # port to amq management
      - "15672:15672"
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq